# Generated by Django 5.1.5 on 2025-02-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='total_piglets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('not_bred', 'ยังไม่ผสม'), ('ready', 'พร้อมผสม'), ('bred', 'ผสมแล้ว'), ('waiting', 'รอคลอด')], default='not_bred', max_length=50),
        ),
        migrations.CreateModel(
            name='Piglet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('alive_count', models.IntegerField(default=0)),
                ('dead_count', models.IntegerField(default=0)),
                ('deformed_count', models.IntegerField(default=0)),
                ('breeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piglets', to='myapp.breedingrecord')),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pig_piglets', to='myapp.pig')),
            ],
        ),
    ]
