# Generated by Django 5.0.3 on 2024-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("boss", "หัวหน้า"), ("employee", "พนักงาน")],
                max_length=10,
                null=True,
            ),
        ),
    ]
