# Generated by Django 5.1.5 on 2025-02-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_total_piglets_breedingrecord_alive_piglets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingrecord',
            old_name='alive_piglets',
            new_name='total_piglets',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='dead_piglets',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='deformed_piglets',
        ),
        migrations.CreateModel(
            name='Piglet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('alive_count', models.IntegerField(default=0)),
                ('dead_count', models.IntegerField(default=0)),
                ('deformed_count', models.IntegerField(default=0)),
                ('breeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piglets', to='myapp.breedingrecord')),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pig_piglets', to='myapp.pig')),
            ],
        ),
    ]
