# Generated by Django 5.1.5 on 2025-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_alive_piglets_breedingrecord_total_piglets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingrecord',
            old_name='total_piglets',
            new_name='alive_piglets',
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='dead_piglets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='deformed_piglets',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Piglet',
        ),
    ]
