# Generated by Django 5.0.3 on 2024-12-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_id_card_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='breed',
        ),
        migrations.AddField(
            model_name='pig',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='pig',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pig',
            name='zone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
