# Generated by Django 5.1.5 on 2025-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_total_piglets_breedingrecord_alive_piglets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='insemination_image',
            field=models.ImageField(blank=True, null=True, upload_to='insemination_images/'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
