# Generated by Django 5.0.3 on 2024-12-15 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_insemination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insemination',
            name='pig_id',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='pig_name',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='weight',
        ),
        migrations.AddField(
            model_name='insemination',
            name='pig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.pig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pig',
            name='address_lock',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pig',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pig_images/'),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='insemination_images/'),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='semen_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('ผสมแล้ว', 'ผสมแล้ว')], default='ปกติ', max_length=10),
        ),
        migrations.AlterField(
            model_name='pig',
            name='zone',
            field=models.CharField(max_length=5),
        ),
    ]
