# Generated by Django 5.1.5 on 2025-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_breedingrecord_insemination_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('not_bred', 'ยังไม่ผสม'), ('ready', 'พร้อมผสม'), ('bred', 'ผสมแล้ว'), ('delivered', 'คลอดแล้ว')], default='not_bred', max_length=50),
        ),
    ]
