# Generated by Django 5.1.5 on 2025-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_pig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='check_heat_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pig',
            name='need_rebreeding',
            field=models.BooleanField(default=False),
        ),
    ]
