# Generated by Django 5.0.3 on 2025-01-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_insemination_insemination_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insemination',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='insemination_result',
            field=models.CharField(choices=[('สำเร็จ', 'สำเร็จ'), ('ล้มเหลว', 'ล้มเหลว')], default='ล้มเหลว', max_length=10),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='pig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pig'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('ผสมแล้ว', 'ผสมแล้ว')], default='ปกติ', max_length=10),
        ),
        migrations.AlterField(
            model_name='pig',
            name='zone',
            field=models.CharField(max_length=5),
        ),
    ]
