# Generated by Django 5.1.4 on 2025-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pig_check_heat_date_pig_need_rebreeding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='check_heat_date',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='need_rebreeding',
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('not_bred', 'ยังไม่ผสม'), ('ready', 'พร้อมผสม'), ('bred', 'ผสมแล้ว'), ('waiting', 'รอคลอด')], default='not_bred', max_length=50),
        ),
    ]
