# Generated by Django 5.1.5 on 2025-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_pig_check_heat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='is_genital_swollen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pig',
            name='is_in_heat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('not_bred', 'ยังไม่ผสม'), ('ready', 'พร้อมผสม'), ('bred', 'ผสมแล้ว'), ('delivered', 'คลอดแล้ว')], default='not_bred', max_length=50),
        ),
    ]
