# Generated by Django 5.0.3 on 2025-01-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_insemination_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='img',
        ),
        migrations.AddField(
            model_name='pig',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pig',
            name='address_lock',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pig',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready for Breeding'), ('waiting', 'Waiting for Delivery')], default='ready', max_length=50),
        ),
        migrations.AlterField(
            model_name='pig',
            name='zone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('semen_id', models.CharField(max_length=50)),
                ('insemination_count', models.IntegerField(default=1)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='myapp.pig')),
            ],
        ),
        migrations.DeleteModel(
            name='Insemination',
        ),
    ]
