# Generated by Django 5.0.3 on 2025-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_pig_img_pig_name_alter_pig_address_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pigs/'),
        ),
    ]
