# Generated by Django 5.1.5 on 2025-03-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pig_is_genital_swollen_pig_is_in_heat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingrecord',
            name='insemination_count',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='insemination_image',
        ),
    ]
