# Generated by Django 5.1.5 on 2025-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_breedingrecord_insemination_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='zone',
        ),
        migrations.AddField(
            model_name='pig',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
