# Generated by Django 5.1.5 on 2025-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='export_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
