# Generated by Django 5.1.5 on 2025-03-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_breedingrecord_export_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingrecord',
            name='export_date',
        ),
        migrations.CreateModel(
            name='PigletExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pig')),
            ],
        ),
    ]
