# Generated by Django 5.1.5 on 2025-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_breedingrecord_export_date_pigletexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
