# Generated by Django 5.1.5 on 2025-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_breedingrecord_export_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingrecord',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PigletExport',
        ),
    ]
