# Generated by Django 5.1.6 on 2025-03-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_breedingrecord_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingrecord',
            old_name='actual_delivery_date',
            new_name='actual_date',
        ),
    ]
