# Generated by Django 5.1.1 on 2025-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_actual_delivery_date_breedingrecord_actual_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
